const pokespriteSupportedFormKeys: Record<string, readonly string[]> = {
  abomasnow: ["mega"],
  absol: ["mega"],
  aegislash: ["blade", "shield"],
  aerodactyl: ["mega"],
  aggron: ["mega"],
  alakazam: ["mega"],
  altaria: ["mega"],
  ampharos: ["mega"],
  araquanid: ["totem"],
  arceus: [
    "bug",
    "dark",
    "dragon",
    "electric",
    "fairy",
    "fighting",
    "fire",
    "flying",
    "ghost",
    "grass",
    "ground",
    "ice",
    "normal",
    "poison",
    "psychic",
    "rock",
    "steel",
    "unknown",
    "water",
  ],
  audino: ["mega"],
  banette: ["mega"],
  basculin: ["blue-striped", "red-striped"],
  beedrill: ["mega"],
  blastoise: ["mega"],
  blaziken: ["mega"],
  burmy: ["plant", "sandy", "trash"],
  camerupt: ["mega"],
  castform: ["rainy", "snowy", "sunny"],
  charizard: ["mega-x", "mega-y"],
  cherrim: ["overcast", "sunshine"],
  darmanitan: ["standard", "zen"],
  deerling: ["autumn", "spring", "summer", "winter"],
  deoxys: ["attack", "defense", "normal", "speed"],
  diancie: ["mega"],
  diglett: ["alola"],
  dugtrio: ["alola"],
  eevee: ["starter"],
  exeggutor: ["alola"],
  flabebe: ["blue", "orange", "red", "white", "yellow"],
  floette: ["blue", "eternal", "orange", "red", "white", "yellow"],
  florges: ["blue", "orange", "red", "white", "yellow"],
  furfrou: [
    "dandy",
    "debutante",
    "diamond",
    "heart",
    "kabuki",
    "la-reine",
    "matron",
    "natural",
    "pharaoh",
    "star",
  ],
  gallade: ["mega"],
  garchomp: ["mega"],
  gardevoir: ["mega"],
  gastrodon: ["east", "west"],
  genesect: ["burn", "chill", "douse", "shock", "standard"],
  gengar: ["mega"],
  geodude: ["alola"],
  giratina: ["altered", "origin"],
  glalie: ["mega"],
  golem: ["alola"],
  gourgeist: ["average", "large", "small", "super"],
  graveler: ["alola"],
  greninja: ["ash", "battle-bond"],
  grimer: ["alola"],
  groudon: ["primal"],
  gumshoos: ["totem"],
  gyarados: ["mega"],
  heracross: ["mega"],
  hoopa: ["unbound"],
  houndoom: ["mega"],
  kangaskhan: ["mega"],
  keldeo: ["ordinary", "resolute"],
  "kommo-o": ["totem"],
  kyogre: ["primal"],
  kyurem: ["black", "white"],
  landorus: ["incarnate", "therian"],
  latias: ["mega"],
  latios: ["mega"],
  lopunny: ["mega"],
  lucario: ["mega"],
  lurantis: ["totem"],
  lycanroc: ["dusk", "midday", "midnight"],
  magearna: ["original"],
  manectric: ["mega"],
  marowak: ["alola", "totem", "totem-alola"],
  marshadow: ["gen7"],
  mawile: ["mega"],
  medicham: ["mega"],
  meloetta: ["aria", "pirouette"],
  meowth: ["alola"],
  metagross: ["mega"],
  mewtwo: ["mega-x", "mega-y"],
  mimikyu: ["busted", "disguised", "totem", "totem-busted", "totem-disguised"],
  minior: [
    "blue",
    "blue-gen7",
    "blue-meteor",
    "green",
    "green-gen7",
    "green-meteor",
    "indigo",
    "indigo-gen7",
    "indigo-meteor",
    "orange",
    "orange-gen7",
    "orange-meteor",
    "red",
    "red-gen7",
    "red-meteor",
    "violet",
    "violet-gen7",
    "violet-meteor",
    "yellow",
    "yellow-gen7",
    "yellow-meteor",
  ],
  mothim: ["plant", "sandy", "trash"],
  muk: ["alola"],
  necrozma: ["dawn", "dusk", "ultra"],
  ninetales: ["alola"],
  oricorio: ["baile", "pau", "pom-pom", "sensu"],
  persian: ["alola"],
  pichu: ["spiky-eared"],
  pidgeot: ["mega"],
  pikachu: [
    "alola-cap",
    "belle",
    "cosplay",
    "hoenn-cap",
    "kalos-cap",
    "libre",
    "original-cap",
    "partner-cap",
    "phd",
    "pop-star",
    "rock-star",
    "sinnoh-cap",
    "starter",
    "unova-cap",
    "world-cap",
  ],
  pinsir: ["mega"],
  pumpkaboo: ["average", "large", "small", "super"],
  raichu: ["alola"],
  raticate: ["alola", "totem", "totem-alola"],
  rattata: ["alola"],
  rayquaza: ["mega"],
  ribombee: ["totem"],
  rockruff: ["own-tempo"],
  rotom: ["fan", "frost", "heat", "mow", "wash"],
  sableye: ["mega"],
  salamence: ["mega"],
  salazzle: ["totem"],
  sandshrew: ["alola"],
  sandslash: ["alola"],
  sawsbuck: ["autumn", "spring", "summer", "winter"],
  scatterbug: [
    "archipelago",
    "continental",
    "elegant",
    "fancy",
    "garden",
    "high-plains",
    "icy-snow",
    "jungle",
    "marine",
    "meadow",
    "modern",
    "monsoon",
    "ocean",
    "poke-ball",
    "polar",
    "river",
    "sandstorm",
    "savanna",
    "sun",
    "tundra",
  ],
  sceptile: ["mega"],
  scizor: ["mega"],
  sharpedo: ["mega"],
  shaymin: ["land", "sky"],
  shellos: ["east", "west"],
  silvally: [
    "bug",
    "dark",
    "dragon",
    "electric",
    "fairy",
    "fighting",
    "fire",
    "flying",
    "ghost",
    "grass",
    "ground",
    "ice",
    "normal",
    "poison",
    "psychic",
    "rock",
    "steel",
    "water",
  ],
  slowbro: ["mega"],
  slowpoke: ["galar"],
  spewpa: [
    "archipelago",
    "continental",
    "elegant",
    "fancy",
    "garden",
    "high-plains",
    "icy-snow",
    "jungle",
    "marine",
    "meadow",
    "modern",
    "monsoon",
    "ocean",
    "poke-ball",
    "polar",
    "river",
    "sandstorm",
    "savanna",
    "sun",
    "tundra",
  ],
  spinda: ["blank", "filled"],
  steelix: ["mega"],
  swampert: ["mega"],
  thundurus: ["incarnate", "therian"],
  togedemaru: ["totem"],
  tornadus: ["incarnate", "therian"],
  tyranitar: ["mega"],
  unown: [
    "a",
    "b",
    "c",
    "d",
    "e",
    "exclamation",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "question",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
  ],
  venusaur: ["mega"],
  vikavolt: ["totem"],
  vivillon: [
    "archipelago",
    "continental",
    "elegant",
    "fancy",
    "garden",
    "high-plains",
    "icy-snow",
    "jungle",
    "marine",
    "meadow",
    "modern",
    "monsoon",
    "ocean",
    "poke-ball",
    "polar",
    "river",
    "sandstorm",
    "savanna",
    "sun",
    "tundra",
  ],
  vulpix: ["alola"],
  wishiwashi: ["school", "solo"],
  wormadam: ["plant", "sandy", "trash"],
  xerneas: ["active", "neutral"],
  zygarde: ["10", "50", "complete"],
};

export function isPokeSpriteSupportedPokemonForm(
  speciesSlug: string,
  formKey: string,
): boolean {
  return pokespriteSupportedFormKeys[speciesSlug]?.includes(formKey) ?? false;
}
